name: flutter_components
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.2.3
  country_pickers: ^2.0.0
  flutter:
    sdk: flutter

  lottie: ^2.1.0
  google_fonts: ^4.0.4
  pinput: ^2.2.21
  graphql_flutter: ^5.1.1
  fluttertoast: ^8.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/animations/
