name: flutter_components
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.2.3
  country_pickers: ^2.0.0
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.20
  flutter_svg: ^2.0.4
  get: ^4.6.5
  lottie: ^2.1.0
  google_fonts: ^6.1.0
  pinput: ^3.0.1
  graphql_flutter: ^5.1.1
  fluttertoast: ^8.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  assets:
    - assets/animations/
